### ISSUE TITLE
Getting "TypeError: utils.$getAncestor is not a function" error

### ISSUE THREAD

**Issue by vishnusatheeshpulickal** [mdx-editor/editor#185]
I want to contribute by adding some more examples to the repo and also understand more by doing this . I encountered an issue while attempting to press the Enter button on the editor as shown below. I kindly request to help me in this regards.

`utils.$getAncestor is not a function
TypeError: utils.$getAncestor is not a function
    at RangeSelection.insertParagraph (http://localhost:3000/static/js/bundle.js:65896:25)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:22481:15)
    at triggerCommandListeners (http://localhost:3000/static/js/bundle.js:67437:29)
    at dispatchCommand (http://localhost:3000/static/js/bundle.js:60718:10)
    at LexicalEditor.dispatchCommand (http://localhost:3000/static/js/bundle.js:68993:12)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:22635:19)
    at triggerCommandListeners (http://localhost:3000/static/js/bundle.js:67437:29)
    at http://localhost:3000/static/js/bundle.js:67421:19
    at beginUpdate (http://localhost:3000/static/js/bundle.js:67547:5)
    at updateEditor (http://localhost:3000/static/js/bundle.js:67623:5)`

**Comment by vishnusatheeshpulickal** [comment]
Here is context for above reported issue. Since issue is closed kindly let me know if I have to create a new issue for the same.

**Issue** :
I encountered an issue while attempting to press the Enter for adding new line on the editor as shown below. I am using CRA setup for developing these examples

**Code snippet**:
```javascript
import {
  MDXEditor,
  headingsPlugin,
  UndoRedo,
  BoldItalicUnderlineToggles,
  toolbarPlugin,
  markdownShortcutPlugin,
  listsPlugin,
  linkPlugin,
  linkDialogPlugin,
  quotePlugin,
  frontmatterPlugin,
  diffSourcePlugin,
  tablePlugin,
  ListsToggle,
  Separator,
  BlockTypeSelect,
  CreateLink,
  InsertImage,
  DiffSourceToggleWrapper,
  InsertTable,
  directivesPlugin,
  AdmonitionDirectiveDescriptor,
  thematicBreakPlugin,
  imagePlugin,
  MDXEditorMethods,
  InsertFrontmatter,
  jsxPlugin,
  JsxComponentDescriptor,
  CodeBlockEditorDescriptor,
  useCodeBlockEditorContext,
  codeBlockPlugin,
  codeMirrorPlugin,
  
} from "@mdxeditor/editor";
import "@mdxeditor/editor/style.css";

const frontmatterMarkdown = `# hello 
- a
- b

> hello world
- a
- b

`;
function DocumentEditor() {
  return (
    <div className="w-full max-h-80vh mt-2 mb-1 overflow-auto scroll-hide bg-white rounded-lg">
      <MDXEditor
        markdown={frontmatterMarkdown}
        plugins={[
          frontmatterPlugin(),
          listsPlugin(),
          tablePlugin(),
          quotePlugin(),
          headingsPlugin(),
          thematicBreakPlugin(),
          linkPlugin(),
          linkDialogPlugin(),
          imagePlugin(),
          codeBlockPlugin(),
          toolbarPlugin({
            toolbarContents: () => (
              <>
                <DiffSourceToggleWrapper>
                  <UndoRedo />
                  <BoldItalicUnderlineToggles />

                  <ListsToggle />
                  <Separator />
                  <BlockTypeSelect />
                  <CreateLink />
                  <InsertImage />
                  <InsertTable />
                </DiffSourceToggleWrapper>
              </>
            ),
          }),
          markdownShortcutPlugin(),
          diffSourcePlugin({
            diffMarkdown: "An older version",
            viewMode: "rich-text",
          }),
        ]}
   
        contentEditableClassName="prose"
        onChange={(e) => console.log(e)}
      />
    </div>
  );
}
```


**Error message**:
  `utils.$getAncestor is not a function
TypeError: utils.$getAncestor is not a function
    at RangeSelection.insertParagraph (http://localhost:3000/static/js/bundle.js:65896:25)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:22481:15)
    at triggerCommandListeners (http://localhost:3000/static/js/bundle.js:67437:29)
    at dispatchCommand (http://localhost:3000/static/js/bundle.js:60718:10)
    at LexicalEditor.dispatchCommand (http://localhost:3000/static/js/bundle.js:68993:12)
    at Array.<anonymous> (http://localhost:3000/static/js/bundle.js:22635:19)
    at triggerCommandListeners (http://localhost:3000/static/js/bundle.js:67437:29)
    at http://localhost:3000/static/js/bundle.js:67421:19
    at beginUpdate (http://localhost:3000/static/js/bundle.js:67547:5)
    at updateEditor (http://localhost:3000/static/js/bundle.js:67623:5)`

**Comment by petyosi** [comment]
Here's a [codesandbox with the code](https://codesandbox.io/p/sandbox/confident-snyder-st2fln?file=/src/App.tsx:14,1) from above. I typed and pressed enter here and there, but I could not reproduce the problem you experience.

**Comment by vishnusatheeshpulickal** [comment]
Thank you for the help. While the code runs smoothly in CodeSandbox, I've identified a minor issues on integrating to a CRA project. 

Info:
Version of package : 1.10.1
React DOM : 18.2.0
React Script : 5.0.1


Issue: Upon including the toobar plugin we get following error log

`
A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (http://localhost:3000/static/js/bundle.js:138411:39)
    at handleError (http://localhost:3000/static/js/bundle.js:144593:11)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:144704:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:144193:24)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:144402:24)
    at flushSyncCallbacks (http://localhost:3000/static/js/bundle.js:132423:26)
    at http://localhost:3000/static/js/bundle.js:144024:17
`

Code snippet (without <Suspense/>)

```javascript
 <MDXEditor
        markdown={frontmatterMarkdown}
        plugins={[
          frontmatterPlugin(),
          listsPlugin(),
          tablePlugin(),
          quotePlugin(),
          headingsPlugin(),
          thematicBreakPlugin(),
          linkPlugin(),
          linkDialogPlugin(),
          imagePlugin(),
          codeBlockPlugin(),
          toolbarPlugin({
            toolbarContents: () => (
              <>
                <DiffSourceToggleWrapper>
                  <UndoRedo />
                  <BoldItalicUnderlineToggles />

                  <ListsToggle />
                  <Separator />
                  <BlockTypeSelect />
                  <CreateLink />
                  <InsertImage />
                  <InsertTable />
                </DiffSourceToggleWrapper>
               </>
            ),
          }),
          markdownShortcutPlugin(),
          diffSourcePlugin({
            diffMarkdown: "An older version",
            viewMode: "rich-text",
          }),
        ]}
   
        contentEditableClassName="prose"
        onChange={(e) => console.log(e)}
      />

```


Solution:
 Use  <Suspence/> in the App.tsx as shown below 

```javascript
<Suspense fallback={<div>loading</div>}>
   <Routes>
    ........
    </Routes>
</Suspense>
```
