### ISSUE TITLE
Error when deleting a thematic break

### ISSUE THREAD

**Issue by AndrewAmgad** [mdx-editor/editor#252]
Hi,

I'm having an issue with deleting thematic breaks. Once inserted, it can only be deleted by pressing backspace twice. However, doing the following throws an error:

1) Insert a thematic break
2) Press on backspace once (this causes the caret to disappear)
3) Now press on the thematic break line or slightly above or below it to place the caret under the line
4) Press on backspace again

This the error I'm seeing:

`Uncaught Error: updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.
    at beginUpdate (Lexical.dev.js:8229:1)
    at updateEditor (Lexical.dev.js:8282:1)
    at LexicalEditor.update (Lexical.dev.js:9798:1)
    at triggerCommandListeners (Lexical.dev.js:8079:1)
    at dispatchCommand (Lexical.dev.js:1237:1)
    at HTMLDivElement.eventHandler (Lexical.dev.js:3064:1)`

The issue can be re-produced on the live demo as well, it shows the following error on the console logs:
`Uncaught Error: Minified Lexical error #19; visit https://lexical.dev/docs/error?code=19 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Z (593-b5b58497930ed062.js:5:31202)
    at n7 (593-b5b58497930ed062.js:5:103168)
    at n8 (593-b5b58497930ed062.js:5:103784)
    at rh.update (593-b5b58497930ed062.js:5:117199)
    at n6 (593-b5b58497930ed062.js:5:100395)
    at tA (593-b5b58497930ed062.js:5:45526)
    at e._lexicalHandled.e._lexicalHandled (593-b5b58497930ed062.js:5:115732)`

**Comment by makkeu** [comment]
This still seems to be an issue. Can be reproduced on demo page:

1. Insert thematic break
2. Click on  thematic break
3. Cursor moves just below it
4. Press backspace

It causes an error in console and editor stops responding.

On my own dev environment, I get this error:

Error: updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.

Followed by

Error: Point.getNode: node not found

**Comment by petyosi** [comment]
I see it, the "just below" part was the missing piece.

**Comment by AndrewAmgad** [comment]
I can see the same issue can be reproduced on the Lexical Playground though (https://playground.lexical.dev), so not sure if it's something that can be resolved here?

**Comment by petyosi** [comment]
It can certainly be a problem in Lexical, but I'm not shy of sending PRs to the project, the team there is great and very perceptive to improvements. Goes without saying, if you want to give it a try, go ahead. The Lexical code is not hard to deal with.

**Comment by AndrewAmgad** [comment]
Not having much luck figuring it out unfortunately, if you have the time to look at it that would be awesome, otherwise I will open an issue there as well.
