### ISSUE TITLE
[BUG] When doing a production build I got Lexical error

### ISSUE THREAD

**Issue by denisvely** [mdx-editor/editor#555]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
I got an error:
Lexical.prod.mjs:9 Uncaught SyntaxError: Invalid regular expression: /^[^A-Za-z�-��-��-??-??-???-??-??-?]*[?-??-??-?]/: Range out of order in character class (at Lexical.prod.mjs:9:1073)
    at new RegExp (<anonymous>)
    at ./modules/Wysiwyg/index.js (Lexical.prod.mjs:9:1073)
    at __webpack_require__ (bootstrap:19:1)
    at ./modules/Rows/SingleRow.js (UploadedDocumentRow.js:55:41)
    at __webpack_require__ (bootstrap:19:1)
    at ./modules/Rows/index.js (SingleRow.js:126:25)
    at __webpack_require__ (bootstrap:19:1)
    at ./common/CustomFields/index.js (CustomFields.js:152:16)
    at __webpack_require__ (bootstrap:19:1)
    at ./pages/Contacts/index.js (serviceFormDataReshaper.js:83:2)

when building a production with webpack.

As I understood lexical is dependency for mdx-editor/editor.
Do you have any suggestions how to fix it?

**Reproduction**
Unfortunately can't provide anything at all. Just looking for an advice.

**Expected behavior**
Building a project without an error.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome, Mozilla

**Note**: It's working on **2.20.0**

**Comment by petyosi** [comment]
Sorry, no idea without a reproduction. Maybe something in Lexical not happy with your bundler.
