### ISSUE TITLE
Error thrown on 'break' 

### ISSUE THREAD

**Issue by jwbackhouse** [mdx-editor/editor#67]
We are getting this console error thrown for certain existing data, which appears to be related to line breaks:
```
Error: no MdastImportVisitor found for break {"type":"break","position":{"start":{"line":1,"column":52,"offset":51},"end":{"line":2,"column":1,"offset":55}}}
    at Ft (importMarkdownToLexical.js:31:13)
    at importMarkdownToLexical.js:21:43
    at Array.forEach (<anonymous>)
    at At (importMarkdownToLexical.js:21:24)
    at Object.addAndStepInto (importMarkdownToLexical.js:45:13)
    at Object.visitNode (MdastParagraphVisitor.js:9:15)
    at Ft (importMarkdownToLexical.js:35:13)
    at importMarkdownToLexical.js:21:43
    at Array.forEach (<anonymous>)
    at Object.At [as visitChildren] (importMarkdownToLexical.js:21:24)
    at Object.visitNode (MdastRootVisitor.js:4:13)
    at Ft (importMarkdownToLexical.js:35:13)
    at W (importMarkdownToLexical.js:60:3)
    at ne (importMarkdownToLexical.js:13:3)
    at index.js:156:5
    at LexicalComposer.prod.js:8:445
    at Do (Lexical.prod.js:176:1)
    at $a (Lexical.prod.js:177:230)
    at wu.update (Lexical.prod.js:205:149)
    at l (LexicalComposer.prod.js:8:409)
    at LexicalComposer.prod.js:9:328
    at Object.useMemo (react-dom.production.min.js:184:189)
    at y.useMemo (react.production.min.js:25:208)
    at y.LexicalComposer (LexicalComposer.prod.js:9:72)
... stack trace continues but React-related only 
```

The data is coming from a Postgres database, which has the following content in a text field:
```
You have the right to a safe and healthy workplace!
You, your supervisors,  and the Co-op work together to make sure our spaces are safe for staff and customers.
```

I cannot replicate it by manually re-entering the string. Based on the error, I assume Lexical is somehow not happy with the line break, but afraid I cannot make any more progress.

Thanks for the help ❤️

**Comment by petyosi** [comment]
I saw that briefly once but can't reproduce :(. I want to find the right markdown string to do so. Any hints from your side?

**Comment by jwbackhouse** [comment]
Found the cause - it happens when a line break (`\n`) is preceded by two or more spaces. So this will cause the error above:
```
Hello  \nWorld
```

**Comment by petyosi** [comment]
Thank you, nice catch. A fixed version is being built and will be released in a few minutes.

**Comment by jwbackhouse** [comment]
Just tested it out and it's working perfectly. Thanks for the super-fast turnaround (again) 🙏🏼 

Not sure what you think about this, but I wonder if it's possible to allow the editor to handle any unexpected markdown gracefully and just render it as a string?
For instance, if the string provided in the `markdown` prop contains a link - `[link](https://link.com)` -, it will throw an error if the `linkPlugin()` hasn't been added. For our use case where we're using the editor to handle existing content, it would be nice if it just rendered that out as plain text

**Comment by petyosi** [comment]
That's interesting idea. Definitely not something I want to enable by default, but maybe provide a hook for catchAll behavior. I will think about it.

**Comment by jwbackhouse** [comment]
That makes sense, can definitely see why you wouldn't want it as the default 👍
