### ISSUE TITLE
no MdastImportVisitor found for *

### ISSUE THREAD

**Issue by HiceS** [mdx-editor/editor#69]
Hey all,

Not sure if anyone else has run into this but with the newest version of CRA im getting the following error while loading the `MDXEditor` component.

There were also many warnings about missing mappings for `react-diff-view` package but you can safely ignore those.

Looks like the mdast package is not resolving the header. I am using `mdast-util-from-markdown` and `mdast-util-gfm-table` within my application for creating my own custom markdown viewer for a separate part of the application. 

```
no MdastImportVisitor found for heading {"type":"heading","depth":1,"children":[{"type":"text","value":"Hello world","position":{"start":{"line":1,"column":3,"offset":2},"end":{"line":1,"column":14,"offset":13}}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":14,"offset":13}}}
    at visit (http://localhost:3000/static/js/bundle.js:125781:13)
    at http://localhost:3000/static/js/bundle.js:125771:41
    at Array.forEach (<anonymous>)
    at Object.visitChildren (http://localhost:3000/static/js/bundle.js:125771:24)
    at Object.visitNode (http://localhost:3000/static/js/bundle.js:126172:13)
    at visit (http://localhost:3000/static/js/bundle.js:125785:13)
    at importMdastTreeToLexical (http://localhost:3000/static/js/bundle.js:125810:3)
    at importMarkdownToLexical (http://localhost:3000/static/js/bundle.js:125755:3)
    at http://localhost:3000/static/js/bundle.js:126414:89
    at http://localhost:3000/static/js/bundle.js:12208:15

ERROR
no MdastImportVisitor found for heading {"type":"heading","depth":1,"children":[{"type":"text","value":"Hello world","position":{"start":{"line":1,"column":3,"offset":2},"end":{"line":1,"column":14,"offset":13}}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":14,"offset":13}}}
    at visit (http://localhost:3000/static/js/bundle.js:125781:13)
    at http://localhost:3000/static/js/bundle.js:125771:41
    at Array.forEach (<anonymous>)
    at Object.visitChildren (http://localhost:3000/static/js/bundle.js:125771:24)
    at Object.visitNode (http://localhost:3000/static/js/bundle.js:126172:13)
    at visit (http://localhost:3000/static/js/bundle.js:125785:13)
    at importMdastTreeToLexical (http://localhost:3000/static/js/bundle.js:125810:3)
    at importMarkdownToLexical (http://localhost:3000/static/js/bundle.js:125755:3)
    at http://localhost:3000/static/js/bundle.js:126414:89
    at http://localhost:3000/static/js/bundle.js:12208:15

ERROR
no MdastImportVisitor found for heading {"type":"heading","depth":1,"children":[{"type":"text","value":"Hello world","position":{"start":{"line":1,"column":3,"offset":2},"end":{"line":1,"column":14,"offset":13}}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":14,"offset":13}}}
    at visit (http://localhost:3000/static/js/bundle.js:125781:13)
    at http://localhost:3000/static/js/bundle.js:125771:41
    at Array.forEach (<anonymous>)
    at Object.visitChildren (http://localhost:3000/static/js/bundle.js:125771:24)
    at Object.visitNode (http://localhost:3000/static/js/bundle.js:126172:13)
    at visit (http://localhost:3000/static/js/bundle.js:125785:13)
    at importMdastTreeToLexical (http://localhost:3000/static/js/bundle.js:125810:3)
    at importMarkdownToLexical (http://localhost:3000/static/js/bundle.js:125755:3)
    at http://localhost:3000/static/js/bundle.js:126414:89
    at http://localhost:3000/static/js/bundle.js:12208:15
```

**Comment by HiceS** [comment]
Example of code 

```
import { MDXEditor } from "@mdxeditor/editor"
import '@mdxeditor/editor/style.css'

export default function NewProcedure() {
    return (
        <>
            <MDXEditor markdown='# Hello world' />
        </>
    )
}
```

**Comment by petyosi** [comment]
You are missing the headingsPlugin.

**Comment by vignesh-gupta** [comment]
@petyosi I'm facing the same issue
Code-
```tsx
<MDXEditor
        onChange={handleChange}
        readOnly={isPreview}
        className={clsx(
          "border-gray-600 border-1 rounded-lg w-full",
          theme === "dark" && "dark-theme dark-editor"
        )}
        markdown={markdown}
        plugins={[
          toolbarPlugin({
            toolbarContents: () => {
              if (isPreview) return <></>;

              return (
                <div className="flex flex-wrap">
                  <UndoRedo /> <BoldItalicUnderlineToggles /> <InsertTable />
                  <BlockTypeSelect /> <CreateLink />  <ListsToggle />
                </div>
              );
            },
          }),
          listsPlugin(),
          quotePlugin(),
          headingsPlugin(),
          linkPlugin(),
          linkDialogPlugin(),
          tablePlugin(),
          thematicBreakPlugin(),
          frontmatterPlugin(),
          codeBlockPlugin({ defaultCodeBlockLanguage: "txt" }),
          codeMirrorPlugin({
            codeBlockLanguages: {
              js: "JavaScript",
              css: "CSS",
              txt: "text",
              tsx: "TypeScript",
            },
          }),
          directivesPlugin({
            directiveDescriptors: [AdmonitionDirectiveDescriptor],
          }),
          diffSourcePlugin({ viewMode: "rich-text", diffMarkdown: "boo" }),
          markdownShortcutPlugin(),
        ]}
      />
```

error-
```ts
Error: no MdastImportVisitor found for heading {"type":"heading","depth":2,"children":[{"type":"text","value":"Day 1: Exploring South Mumbai","position":{"start":{"line":1,"column":4,"offset":3},"end":{"line":1,"column":33,"offset":32}}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":33,"offset":32}}}
```

**Comment by HiceS** [comment]
Thank you, sorry completely missed it.
