### ISSUE TITLE
CodeBlock error when language is not specified in Markdown Text

### ISSUE THREAD

**Issue by razorback16** [mdx-editor/editor#89]
If I remove the code language from the block like this in the Markdown text

\```
export default function App() {
  return (<div>Hello world</div>)
}
\```

The I am getting this error. 

```
ERROR
No CodeBlockEditor registered for language=null meta=null
    at CodeBlockEditorContainer (http://localhost:3000/static/js/bundle.js:158905:11)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60394:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63680:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:64976:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:49986:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:50030:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:50087:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:69961:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:69208:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:69131:9)
ERROR
No CodeBlockEditor registered for language=null meta=null
    at CodeBlockEditorContainer (http://localhost:3000/static/js/bundle.js:158905:11)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60394:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63680:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:64976:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:49986:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:50030:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:50087:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:69961:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:69208:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:69131:9)
ERROR
No CodeBlockEditor registered for language=null meta=null
    at CodeBlockEditorContainer (http://localhost:3000/static/js/bundle.js:158905:11)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60394:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63680:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:64976:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:69939:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:69208:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:69131:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:69104:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:68596:24)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:68805:24)
ERROR
No CodeBlockEditor registered for language=null meta=null
    at CodeBlockEditorContainer (http://localhost:3000/static/js/bundle.js:158905:11)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60394:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63680:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:64976:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:69939:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:69208:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:69131:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:69104:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:68596:24)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:68805:24)
```

I see similar error on the live demo as well.

**Comment by petyosi** [comment]
That's how the code block plugin is configured. You can adjust it for your requirements: https://mdxeditor.dev/editor/docs/code-blocks.
